export const fishListingsData = [
    {
      id: 1,
      name: "Fresh Salmon",
      price: 12.99,
      image: "https://plus.unsplash.com/premium_photo-1723478431094-4854c4555fc2?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RnJlc2glMjBTYWxtb258ZW58MHx8MHx8fDA%3D",
      fisherman: "John's Fishing Co.",
      location: "Pacific Coast",
      available: true,
      description: "Wild-caught salmon, fresh from the Pacific Ocean. Rich in flavor and omega-3 fatty acids.",
      availableQuantity: 25,
    },
    {
      id: 2,
      name: "Wild Tuna",
      price: 15.99,
      image: "https://media.istockphoto.com/id/958307950/photo/raw-salmon-steak.webp?a=1&b=1&s=612x612&w=0&k=20&c=frK7pQ7Yzc4RXoSswqeyb0oiYvW3JnXCAfdXvJYmFzQ=",
      fisherman: "Ocean Harvest",
      location: "Atlantic Coast",
      available: true,
      description: "Premium tuna caught using sustainable fishing methods. Perfect for sushi or grilling.",
      availableQuantity: 18,
    },
    {
      id: 3,
      name: "Local Trout",
      price: 9.99,
      image: "https://images.unsplash.com/photo-1682942925422-b899fd9b36ce?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fExvY2FsJTIwVHJvdXR8ZW58MHx8MHx8fDA%3D",
      fisherman: "River Catch",
      location: "Mountain Rivers",
      available: true,
      description: "Freshwater trout from pristine mountain rivers. Delicate flavor and firm texture.",
      availableQuantity: 30,
    },
    {
      id: 4,
      name: "King Crab",
      price: 24.99,
      image: "https://images.unsplash.com/photo-1603249594064-268aaca537b0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8S2luZyUyMENyYWJ8ZW58MHx8MHx8fDA%3D",
      fisherman: "Deep Sea Divers",
      location: "Bering Sea",
      available: false,
      description: "Large, meaty king crab legs. Sweet flavor and tender texture. A true delicacy.",
      availableQuantity: 0,
    },
    {
      id: 5,
      name: "Fresh Cod",
      price: 8.99,
      image: "https://plus.unsplash.com/premium_photo-1663040089947-145a84e26a9b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RnJlc2glMjBDb2R8ZW58MHx8MHx8fDA%3D",
      fisherman: "North Atlantic Fisheries",
      location: "North Atlantic",
      available: true,
      description: "Mild, flaky white fish perfect for fish and chips or baking.",
      availableQuantity: 40,
    },
    {
      id: 6,
      name: "Pacific Halibut",
      price: 18.99,
      image: "https://images.unsplash.com/photo-1685674317675-240593074127?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      fisherman: "Pacific Northwest Catch",
      location: "Pacific Northwest",
      available: true,
      description: "Firm, white-fleshed fish with a clean taste. Excellent for grilling or pan-searing.",
      availableQuantity: 15,
    },
    {
      id: 7,
      name: "Atlantic Mackerel",
      price: 7.99,
      image: "https://images.unsplash.com/photo-1639081652598-0d13212f57f2?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      fisherman: "East Coast Fishers",
      location: "East Coast",
      available: true,
      description: "Oily fish with distinctive flavor. Rich in omega-3 fatty acids and perfect for grilling.",
      availableQuantity: 22,
    },
    {
      id: 8,
      name: "Rainbow Trout",
      price: 10.99,
      image: "https://images.unsplash.com/photo-1485452499676-62ab02c20e83?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8UmFpbmJvdyUyMFRyb3V0fGVufDB8fDB8fHww",
      fisherman: "Mountain Stream Fishery",
      location: "Rocky Mountains",
      available: true,
      description: "Farm-raised rainbow trout with clean, mild flavor. Great for baking or pan-frying.",
      availableQuantity: 28,
    },
  ]